// Sri Durga Travels - Constants

export const COMPANY_INFO = {
  name: "Sri Durga Travels",
  tagline: "Your Journey, Our Passion",
  email: "contact@sridurgatravels.com",
  phones: ["+91 86188 25738", "+91 99168 49541"],
  address: "Bengaluru, Karnataka, India",
  experience: "22+",
  trips: "2,000+",
  staff: "100+",
  clients: "450+",
  awards: "80+",
};

export const NAV_LINKS = [
  { name: "Home", href: "/" },
  { name: "About Us", href: "/about" },
  { name: "Cars & Bus Rentals", href: "/rentals" },
  { name: "Trekking", href: "/trekking" },
  { name: "Gallery", href: "/gallery" },
  { name: "Contact Us", href: "/contact" },
];

export const ADMIN_NAV_LINKS = [
  { name: "Dashboard", href: "/admin" },
  { name: "Vehicles", href: "/admin/vehicles" },
  { name: "Treks", href: "/admin/treks" },
  { name: "Bookings", href: "/admin/bookings" },
  { name: "Messages", href: "/admin/messages" },
  { name: "Gallery", href: "/admin/gallery" },
  { name: "Users", href: "/admin/users" },
  { name: "Settings", href: "/admin/settings" },
];

export const VEHICLE_TYPES = {
  car: "Car",
  tempo_traveller: "Tempo Traveller",
  mini_bus: "Mini Bus",
  coach: "Coach",
  luxury_bus: "Luxury Bus",
};

export const TREK_DIFFICULTIES = {
  easy: "Easy",
  moderate: "Moderate",
  challenging: "Challenging",
  difficult: "Difficult",
};

export const BOOKING_STATUSES = {
  pending: { label: "Pending", color: "warning" },
  confirmed: { label: "Confirmed", color: "success" },
  cancelled: { label: "Cancelled", color: "destructive" },
  completed: { label: "Completed", color: "muted" },
};

// Complete vehicle data with exact pricing from Sri Durga Travels
export const DEFAULT_VEHICLES = [
  {
    name: "AC TT 13 Seater (Luxury)",
    type: "tempo_traveller",
    capacity: 13,
    description: "Modern tempo traveller with AC comfort, push-back seats, music system. Perfect for corporate trips, pilgrimages and weddings.",
    features: ["Air Conditioning", "Push-back Seats", "Music System", "Ample Luggage Space", "Professional Driver"],
    base_price: 4500,
    extra_hour_rate: 450,
    extra_km_rate: 29,
    full_day_price: null,
    outstation_allowance: "300 km/day",
    driver_bata: 600,
    image: "/images/vehicles/tt-13-seater.jpg",
  },
  {
    name: "Urbania Luxury 16 Seater",
    type: "tempo_traveller",
    capacity: 16,
    description: "Stylish and spacious Urbania van, suitable for corporate travel, family vacations and airport transfers.",
    features: ["Air Conditioning", "Premium Seating", "Entertainment System", "USB Charging", "Professional Driver"],
    base_price: 7000,
    extra_hour_rate: 450,
    extra_km_rate: 40,
    full_day_price: null,
    outstation_allowance: "300 km/day",
    driver_bata: 700,
    image: "/images/vehicles/urbania-luxury.jpg",
  },
  {
    name: "21 Seater Mini-bus",
    type: "mini_bus",
    capacity: 21,
    description: "Reliable and comfortable mini-bus with ample legroom and AC. Budget-friendly travel for medium-sized groups.",
    features: ["Air Conditioning", "Comfortable Seating", "Ample Legroom", "Clean Interiors", "Trained Driver"],
    base_price: 8500,
    extra_hour_rate: 500,
    extra_km_rate: 38,
    full_day_price: 13000,
    outstation_allowance: null,
    driver_bata: 800,
    image: "/images/vehicles/21-seater.jpeg",
  },
  {
    name: "25 Seater Mini-bus",
    type: "mini_bus",
    capacity: 25,
    description: "Spacious mini-bus with comfortable seating, ideal for cost-effective group travel and corporate outings.",
    features: ["Air Conditioning", "Spacious Interior", "Comfortable Seating", "Luggage Space", "Experienced Driver"],
    base_price: 9500,
    extra_hour_rate: 500,
    extra_km_rate: 45,
    full_day_price: 14000,
    outstation_allowance: null,
    driver_bata: 800,
    image: "/images/vehicles/25-seater.jpeg",
  },
  {
    name: "33 Seater Coach",
    type: "coach",
    capacity: 33,
    description: "Premium bus with panoramic windows, push-back seats and high safety standards. Ideal for large group travel.",
    features: ["Air Conditioning", "Push-back Seats", "Panoramic Windows", "Safety Features", "Experienced Driver"],
    base_price: 11000,
    extra_hour_rate: 600,
    extra_km_rate: 50,
    full_day_price: 16500,
    outstation_allowance: null,
    driver_bata: 900,
    image: "/images/vehicles/33-seater.jpeg",
  },
  {
    name: "49 Seater (3+2)",
    type: "coach",
    capacity: 49,
    description: "Large capacity bus perfect for school trips, corporate events and pilgrimages. Comfortable seating with AC.",
    features: ["Air Conditioning", "3+2 Seating", "Comfortable Interior", "Large Capacity", "Professional Driver"],
    base_price: 12000,
    extra_hour_rate: 600,
    extra_km_rate: 52,
    full_day_price: 17000,
    outstation_allowance: "400 km/day",
    driver_bata: 900,
    image: "/images/vehicles/49-seater.jpeg",
  },
  {
    name: "40 Seater (2+2) Luxury",
    type: "luxury_bus",
    capacity: 40,
    description: "Luxury bus with reclining seats, full AC, entertainment system. Perfect for luxury tours and corporate events.",
    features: ["Air Conditioning", "Reclining Seats", "Entertainment System", "Premium Interiors", "Professional Driver"],
    base_price: 16000,
    extra_hour_rate: 1500,
    extra_km_rate: 65,
    full_day_price: 27000,
    outstation_allowance: null,
    driver_bata: 1250,
    image: "/images/vehicles/40-seater.jpeg",
  },
  {
    name: "Benz 45 Seater (2+2)",
    type: "luxury_bus",
    capacity: 45,
    description: "Premium Mercedes-Benz coach with push-back seats, wide legroom, panoramic windows and high-end suspension.",
    features: ["Air Conditioning", "Premium Push-back Seats", "Wide Legroom", "Panoramic Windows", "Premium Suspension"],
    base_price: 17000,
    extra_hour_rate: 1600,
    extra_km_rate: 70,
    full_day_price: 28000,
    outstation_allowance: null,
    driver_bata: 1300,
    image: "/images/vehicles/benz-45.jpeg",
  },
  {
    name: "Volvo AC 45/49 Seater",
    type: "luxury_bus",
    capacity: 49,
    description: "World-class Volvo bus for corporate tours and long-distance journeys. Full AC with comfortable reclining seats.",
    features: ["Air Conditioning", "Reclining Seats", "World-class Interiors", "Long-distance Comfort", "Expert Driver"],
    base_price: 12000,
    extra_hour_rate: 600,
    extra_km_rate: 52,
    full_day_price: 17000,
    outstation_allowance: "400 km/day",
    driver_bata: 900,
    image: "/images/vehicles/volvo-45-2x2.jpeg",
  },
  // Cars
  {
    name: "Kia Carens",
    type: "car",
    capacity: 7,
    description: "Spacious MPV with 6 passenger seats + driver. Ideal for family trips and airport transfers with reclining seats and entertainment.",
    features: ["Air Conditioning", "Reclining Seats", "Entertainment System", "Spacious Boot", "Professional Driver"],
    base_price: 3500,
    extra_hour_rate: null,
    extra_km_rate: 16,
    full_day_price: 3500,
    outstation_allowance: "Outstation ₹16/km",
    driver_bata: null,
    image: "/images/vehicles/kia-carens.avif",
  },
  {
    name: "Toyota Etios",
    type: "car",
    capacity: 4,
    description: "Reliable and comfortable sedan for city travel and airport transfers. Good mileage with spacious boot.",
    features: ["Air Conditioning", "Comfortable Seating", "Spacious Boot", "Good Mileage", "Professional Driver"],
    base_price: 2200,
    extra_hour_rate: 300,
    extra_km_rate: 18,
    full_day_price: 2200,
    outstation_allowance: "200 km/day",
    driver_bata: 550,
    image: "/images/vehicles/toyota-etios.avif",
  },
  {
    name: "Innova Crysta",
    type: "car",
    capacity: 7,
    description: "Premium MPV with plush seating, strong air-conditioning and stylish design. Perfect for family travel.",
    features: ["Air Conditioning", "Plush Seating", "Stylish Design", "Ample Legroom", "Professional Driver"],
    base_price: 3500,
    extra_hour_rate: 400,
    extra_km_rate: 25,
    full_day_price: 3500,
    outstation_allowance: "250 km/day",
    driver_bata: 600,
    image: "/images/vehicles/innova-crysta.avif",
  },
  {
    name: "Innova Hycross",
    type: "car",
    capacity: 6,
    description: "Hybrid MPV offering excellent mileage and comfort. Premium interiors with captain seats and ample luggage space.",
    features: ["Hybrid Engine", "Captain Seats", "Premium Interiors", "Excellent Mileage", "Ample Luggage Space"],
    base_price: 4000,
    extra_hour_rate: 450,
    extra_km_rate: 30,
    full_day_price: 4000,
    outstation_allowance: "300 km/day",
    driver_bata: 650,
    image: "/images/vehicles/innova-hycross.avif",
  },
];

// Complete trekking packages with exact pricing
export const DEFAULT_TREKS = [
  {
    name: "Kudremukh Trek",
    destination: "Chikkamagaluru",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "1,894 m",
    distance: "20-22 km",
    price_per_person: 3899,
    description: "Trek to the horse-face peak through lush shola forests, streams and rolling hills. Experience stunning panoramic views and wildlife sightings.",
    highlights: ["Stunning panoramic views", "Wildlife sightings", "Shola forests", "Samse Tea Estate visit", "Belur Temple optional visit"],
    image: "/images/treks/kudremukh-trek.jpg",
  },
  {
    name: "Nethravathi Trek",
    destination: "Kudremukh Range",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "1,520 m",
    distance: "18-20 km",
    price_per_person: 3899,
    description: "Scenic trek leading to Nethravathi Peak with views of the Kudremukh range. Pass through shola forests, rolling grasslands and hidden streams.",
    highlights: ["Shola forests", "Rolling grasslands", "Hidden streams", "Panoramic vistas", "Kudremukh range views"],
    image: "/images/treks/nethravathi-trek.jpg",
  },
  {
    name: "Gokarna Beach Trek",
    destination: "Gokarna",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "Sea level",
    distance: "12 km",
    price_per_person: 3299,
    description: "Coastal trek visiting Paradise, Half Moon, Om and Kudle beaches with camping near the shore.",
    highlights: ["Beach camping", "Campfire & star-gazing", "Paradise Beach", "Half Moon Beach", "Om Beach"],
    image: "/images/treks/gokarna-beach.jpg",
  },
  {
    name: "Kodaikanal Tour",
    destination: "Kodaikanal",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "2,133 m",
    distance: "Sightseeing",
    price_per_person: 5499,
    description: "Visit Moir Point, Pine Forest, Pillar Rocks and Bryant Park. Includes boating and strawberry farm visit.",
    highlights: ["Boating", "Pine Forest walk", "Pillar Rocks", "Strawberry farm", "Bryant Park"],
    image: "/images/treks/kodaikanal-tour.jpg",
  },
  {
    name: "Coorg Tour",
    destination: "Coorg",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "1,170 m",
    distance: "Sightseeing",
    price_per_person: 4499,
    description: "Explore Raja's Seat, Mandalpatti, Abbey Falls and coffee plantations with jeep safari and campfire.",
    highlights: ["Mandalpatti Jeep Safari", "Abbey Falls", "Coffee plantation walk", "Campfire", "Raja's Seat"],
    image: "/images/treks/coorg-tour.jpg",
  },
  {
    name: "Ooty Tour",
    destination: "Ooty",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "2,240 m",
    distance: "Sightseeing",
    price_per_person: 5499,
    description: "Visit Pykara Lake & Falls, Pine Forest, Doddabetta Peak and enjoy the famous Ooty Toy Train.",
    highlights: ["Ooty Toy Train", "Pykara Lake", "Doddabetta Peak", "Pine Forest", "Botanical Garden"],
    image: "/images/treks/ooty-tour.jpg",
  },
  {
    name: "Chikkamagaluru Tour",
    destination: "Chikkamagaluru",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "1,998 m",
    distance: "Sightseeing",
    price_per_person: 4499,
    description: "Visit Mullayanagiri sunrise point, Hebbe Falls, coffee estates and Baba Budangiri.",
    highlights: ["Mullayanagiri sunrise", "Hebbe Falls", "Coffee estates", "Baba Budangiri", "Homestay experience"],
    image: "/images/treks/chikmagalur-tour.jpg",
  },
  {
    name: "Wayanad Tour",
    destination: "Wayanad",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "700-2,100 m",
    distance: "Sightseeing",
    price_per_person: 5499,
    description: "Off-road jeep safari to sunset viewpoint, glass bridge, Edakkal Caves and lush tea estates.",
    highlights: ["Jeep Safari", "Glass Bridge", "Edakkal Caves", "Tea Estates", "Campfire"],
    image: "/images/treks/wayanad-tour.jpg",
  },
  {
    name: "Pondicherry Tour",
    destination: "Pondicherry",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "Sea level",
    distance: "Sightseeing",
    price_per_person: 5299,
    description: "Heritage walks, beaches, Auroville, Promenade and French Quarter exploration.",
    highlights: ["French Quarter", "Auroville", "Beach walks", "Promenade", "Heritage sites"],
    image: "/images/treks/pondicherry-tour.jpg",
  },
  {
    name: "Kurinjal Trek",
    destination: "Kudremukh National Park",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "1,640 m",
    distance: "14 km",
    price_per_person: 3299,
    description: "Moderate trek to Kurinjal peak through forests and meadows in Kudremukh National Park.",
    highlights: ["Forest trails", "Meadow views", "Peak sunrise", "Wildlife sightings", "Shola grasslands"],
    image: "/images/treks/kurinjal-trek.jpg",
  },
  {
    name: "Dudhsagar Trek & Dandeli Rafting",
    destination: "Goa-Karnataka Border",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "310 m",
    distance: "Trek + Rafting",
    price_per_person: 4999,
    description: "Trek to the spectacular 300m Dudhsagar Falls combined with white-water rafting in Dandeli.",
    highlights: ["Dudhsagar Falls", "White-water rafting", "Jungle trek", "Campfire", "Adventure combo"],
    image: "/images/treks/dudhsagar-falls.jpg",
  },
  {
    name: "Tadiandamol Trek",
    destination: "Coorg",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "1,748 m",
    distance: "16 km",
    price_per_person: 3299,
    description: "Trek to the highest peak in Coorg district through shola forests and grasslands.",
    highlights: ["Highest peak in Coorg", "Shola forests", "Grassland views", "Sunrise point", "Coffee plantation"],
    image: "/images/treks/tadiandamol-trek.jpg",
  },
  {
    name: "Gangadikal Trek",
    destination: "Kudremukh National Park",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "1,464 m",
    distance: "8 km",
    price_per_person: 3299,
    description: "Trek through tropical forest and shola grasslands to Gangadikal Peak with panoramic views.",
    highlights: ["Sunrise from peak", "Panoramic views", "Biodiversity", "Rolling hills", "Shola grasslands"],
    image: "/images/treks/gangadikal-trek.jpg",
  },
  {
    name: "Kumara Parvatha Trek",
    destination: "Pushpagiri Wildlife Sanctuary",
    duration: "2 Days / 1 Night",
    difficulty: "challenging",
    altitude: "1,712 m",
    distance: "14 km",
    price_per_person: 3299,
    description: "Challenging trek to the 4th highest peak in Karnataka via Somvarpet through shola forests.",
    highlights: ["4th highest peak in Karnataka", "Shola forests", "Rocky scrambles", "Panoramic views", "Forest registration"],
    image: "/images/treks/kumara-parvatha-trek.jpg",
  },
  {
    name: "Kodachadri Trek",
    destination: "Shivamogga",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "1,343 m",
    distance: "24-28 km",
    price_per_person: 3299,
    description: "Trek via Hidlumane Falls to Kodachadri Peak with visits to Devagange Pond and Nagara Fort.",
    highlights: ["Hidlumane Falls", "Devagange Pond", "Nagara Fort", "Sunset views", "Dense forests"],
    image: "/images/treks/kodachadri-trek.jpg",
  },
  {
    name: "Bandaje Falls Trek",
    destination: "Charmadi",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "200 ft falls",
    distance: "15 km",
    price_per_person: 3299,
    description: "Trek to Bandaje Arbi Falls through dense rainforest with visit to Ballalarayana Durga Fort.",
    highlights: ["200 ft waterfall", "Rainforest trail", "Ballalarayana Durga Fort", "Shola grasslands", "Offbeat adventure"],
    image: "/images/treks/bandaje-falls.jpg",
  },
];

export const DEFAULT_TESTIMONIALS = [
  {
    name: "Rajesh Kumar",
    content: "Excellent service! The bus was clean, driver was professional, and everything was on time. Highly recommend Sri Durga Travels for group trips.",
    rating: 5,
  },
  {
    name: "Latha Suresh",
    content: "We booked a tempo traveller for our family pilgrimage. The vehicle was well-maintained and comfortable. Great experience overall!",
    rating: 5,
  },
  {
    name: "Vikram Reddy",
    content: "The trekking package to Kudremukh was amazing! Well-organized trip with experienced guides. Will definitely book again.",
    rating: 5,
  },
  {
    name: "Priya Sharma",
    content: "Booked the Coorg tour for a weekend getaway. Everything was perfectly arranged - from pickup to accommodation. Loved the jeep safari!",
    rating: 5,
  },
  {
    name: "Suresh Nair",
    content: "Used their 49-seater bus for our company outing. Punctual, professional and the bus was in excellent condition. Highly recommended!",
    rating: 5,
  },
];

export const WHY_CHOOSE_US = [
  {
    title: "Affordable Pricing",
    description: "Competitive rates without compromising on quality or comfort.",
    icon: "wallet",
  },
  {
    title: "Well-Maintained Vehicles",
    description: "Our fleet is regularly serviced and kept in top condition.",
    icon: "car",
  },
  {
    title: "Experienced Drivers",
    description: "Professional, courteous drivers with extensive route knowledge.",
    icon: "user",
  },
  {
    title: "On-Time Service",
    description: "Punctuality is our priority - we value your time.",
    icon: "clock",
  },
];
