// Sri Durga Travels - Constants

export const COMPANY_INFO = {
  name: "Sri Durga Travels",
  tagline: "Your Journey, Our Passion",
  email: "contact@sridurgatravels.com",
  phones: ["+91 86188 25738", "+91 99168 49541"],
  address: "Bengaluru, Karnataka, India",
  experience: "22+",
  trips: "2,000+",
  staff: "100+",
  clients: "450+",
  awards: "80+",
};

export const NAV_LINKS = [
  { name: "Home", href: "/" },
  { name: "About Us", href: "/about" },
  { name: "Cars & Bus Rentals", href: "/rentals" },
  { name: "Trekking", href: "/trekking" },
  { name: "Gallery", href: "/gallery" },
  { name: "Contact Us", href: "/contact" },
];

export const ADMIN_NAV_LINKS = [
  { name: "Dashboard", href: "/admin" },
  { name: "Vehicles", href: "/admin/vehicles" },
  { name: "Treks", href: "/admin/treks" },
  { name: "Bookings", href: "/admin/bookings" },
  { name: "Messages", href: "/admin/messages" },
  { name: "Gallery", href: "/admin/gallery" },
  { name: "Users", href: "/admin/users" },
  { name: "Settings", href: "/admin/settings" },
];

export const VEHICLE_TYPES = {
  car: "Car",
  tempo_traveller: "Tempo Traveller",
  mini_bus: "Mini Bus",
  coach: "Coach",
  luxury_bus: "Luxury Bus",
};

export const TREK_DIFFICULTIES = {
  easy: "Easy",
  moderate: "Moderate",
  challenging: "Challenging",
  difficult: "Difficult",
};

export const BOOKING_STATUSES = {
  pending: { label: "Pending", color: "warning" },
  confirmed: { label: "Confirmed", color: "success" },
  cancelled: { label: "Cancelled", color: "destructive" },
  completed: { label: "Completed", color: "muted" },
};

export const DEFAULT_VEHICLES = [
  {
    name: "AC TT 13 Seater (Luxury)",
    type: "tempo_traveller",
    capacity: 13,
    description: "Modern tempo traveller with AC comfort, push-back seats, music system. Perfect for corporate trips, pilgrimages and weddings.",
    features: ["Air Conditioning", "Push-back Seats", "Music System", "Ample Luggage Space", "Professional Driver"],
    base_price: 4500,
    extra_hour_rate: 450,
    extra_km_rate: 29,
    full_day_price: null,
    outstation_allowance: "300 km/day",
    driver_bata: 600,
    image: "/images/vehicles/tempo-traveller-13.jpg",
  },
  {
    name: "Urbania Luxury 16 Seater",
    type: "tempo_traveller",
    capacity: 16,
    description: "Stylish and spacious Urbania van, suitable for corporate travel, family vacations and airport transfers.",
    features: ["Air Conditioning", "Premium Seating", "Entertainment System", "USB Charging", "Professional Driver"],
    base_price: 7000,
    extra_hour_rate: 450,
    extra_km_rate: 40,
    full_day_price: null,
    outstation_allowance: "300 km/day",
    driver_bata: 700,
    image: "/images/vehicles/urbania-luxury-16.jpg",
  },
  {
    name: "21 Seater Mini-bus",
    type: "mini_bus",
    capacity: 21,
    description: "Reliable and comfortable mini-bus with ample legroom and AC. Budget-friendly travel for medium-sized groups.",
    features: ["Air Conditioning", "Comfortable Seating", "Ample Legroom", "Clean Interiors", "Trained Driver"],
    base_price: 8500,
    extra_hour_rate: 500,
    extra_km_rate: 38,
    full_day_price: 13000,
    outstation_allowance: null,
    driver_bata: 800,
    image: "/images/vehicles/minibus-21.jpg",
  },
  {
    name: "33 Seater Coach",
    type: "coach",
    capacity: 33,
    description: "Premium bus with panoramic windows, push-back seats and high safety standards. Ideal for large group travel.",
    features: ["Air Conditioning", "Push-back Seats", "Panoramic Windows", "Safety Features", "Experienced Driver"],
    base_price: 11000,
    extra_hour_rate: 600,
    extra_km_rate: 50,
    full_day_price: 16500,
    outstation_allowance: null,
    driver_bata: 900,
    image: "/images/vehicles/coach-33.jpg",
  },
  {
    name: "40 Seater (2+2) Luxury",
    type: "luxury_bus",
    capacity: 40,
    description: "Luxury bus with reclining seats, full AC, entertainment system. Perfect for luxury tours and corporate events.",
    features: ["Air Conditioning", "Reclining Seats", "Entertainment System", "Premium Interiors", "Professional Driver"],
    base_price: 16000,
    extra_hour_rate: 1500,
    extra_km_rate: 65,
    full_day_price: 27000,
    outstation_allowance: null,
    driver_bata: 1250,
    image: "/images/vehicles/luxury-40.jpg",
  },
  {
    name: "Benz 45 Seater (2+2)",
    type: "luxury_bus",
    capacity: 45,
    description: "Premium Mercedes-Benz coach with push-back seats, wide legroom, panoramic windows and high-end suspension.",
    features: ["Air Conditioning", "Premium Push-back Seats", "Wide Legroom", "Panoramic Windows", "Premium Suspension"],
    base_price: 17000,
    extra_hour_rate: 1600,
    extra_km_rate: 70,
    full_day_price: 28000,
    outstation_allowance: null,
    driver_bata: 1300,
    image: "/images/vehicles/benz-45.jpg",
  },
  {
    name: "Volvo 49 Seater (3+2)",
    type: "luxury_bus",
    capacity: 49,
    description: "World-class Volvo bus for corporate tours and long-distance journeys. Full AC with comfortable reclining seats.",
    features: ["Air Conditioning", "Reclining Seats", "World-class Interiors", "Long-distance Comfort", "Expert Driver"],
    base_price: 12000,
    extra_hour_rate: 600,
    extra_km_rate: 52,
    full_day_price: 17000,
    outstation_allowance: "400 km/day",
    driver_bata: 900,
    image: "/images/vehicles/volvo-49.jpg",
  },
];

export const DEFAULT_TREKS = [
  {
    name: "Kudremukh Trek",
    destination: "Chikkamagaluru",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "1,894 m",
    distance: "20-22 km",
    price_per_person: 3899,
    description: "Trek to the horse-face peak through lush shola forests, streams and rolling hills.",
    highlights: ["Stunning panoramic views", "Wildlife sightings", "Shola forests", "Samse Tea Estate visit"],
    image: "/images/hero/hero-trekking.jpg",
  },
  {
    name: "Nethravathi Trek",
    destination: "Kudremukh Range",
    duration: "2 Days / 1 Night",
    difficulty: "moderate",
    altitude: "1,520 m",
    distance: "18-20 km",
    price_per_person: 3899,
    description: "Scenic trek leading to Nethravathi Peak with views of the Kudremukh range.",
    highlights: ["Shola forests", "Rolling grasslands", "Hidden streams", "Panoramic vistas"],
    image: "/images/hero/hero-trekking.jpg",
  },
  {
    name: "Gokarna Beach Trek",
    destination: "Gokarna",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "Sea level",
    distance: "12 km",
    price_per_person: 3299,
    description: "Coastal trek visiting Paradise, Half Moon, Om and Kudle beaches with camping.",
    highlights: ["Beach camping", "Campfire", "Star-gazing", "Multiple beach visits"],
    image: "/images/hero/hero-trekking.jpg",
  },
  {
    name: "Kodaikanal Tour",
    destination: "Kodaikanal",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "2,133 m",
    distance: "Sightseeing",
    price_per_person: 5499,
    description: "Visit Moir Point, Pine Forest, Pillar Rocks and Bryant Park.",
    highlights: ["Boating", "Pine Forest walk", "Pillar Rocks", "Strawberry farm"],
    image: "/images/hero/hero-trekking.jpg",
  },
  {
    name: "Coorg Tour",
    destination: "Coorg",
    duration: "2 Days / 1 Night",
    difficulty: "easy",
    altitude: "1,170 m",
    distance: "Sightseeing",
    price_per_person: 4499,
    description: "Explore Raja's Seat, Mandalpatti, Abbey Falls and coffee plantations.",
    highlights: ["Jeep Safari", "Abbey Falls", "Coffee plantation walk", "Campfire"],
    image: "/images/hero/hero-trekking.jpg",
  },
];

export const DEFAULT_TESTIMONIALS = [
  {
    name: "Rajesh Kumar",
    content: "Excellent service! The bus was clean, driver was professional, and everything was on time. Highly recommend Sri Durga Travels for group trips.",
    rating: 5,
  },
  {
    name: "Latha Suresh",
    content: "We booked a tempo traveller for our family pilgrimage. The vehicle was well-maintained and comfortable. Great experience overall!",
    rating: 5,
  },
  {
    name: "Vikram Reddy",
    content: "The trekking package to Kudremukh was amazing! Well-organized trip with experienced guides. Will definitely book again.",
    rating: 5,
  },
];
